<?php
http_response_code(404);
include("templates/header.php");
include("sections/header.php");
include("sections/404.php");
include("sections/request-popup.php");
include("sections/message-popup.php");
include("sections/overlay-popup.php");
include("sections/footer.php");
include("templates/footer.php");